/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shortest_paths;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;

/**
 *
 * @author Christina
 */
public class ShortestPathsGUI extends javax.swing.JFrame {
    int startX,startY,endX,endY;
    Node[][] grid;
    /**
     * Creates new form ShortestPathsGUI
     * @throws java.io.FileNotFoundException
     */
    public ShortestPathsGUI() throws FileNotFoundException{
        initComponents();
        File numberFile = new File("NumberMap.txt");
		//BufferedReader numberFileReader = new BufferedReader(new FileReader(numberFile));
        
		if (numberFile.exists()) {
			Scanner numberFileReader = new Scanner(numberFile);
			grid = new Node[20][20];	
			int x = 0,y = 0,num;
			while(numberFileReader.hasNextInt()) {
				num = numberFileReader.nextInt();
				grid[x][y] = new Node(x,y,num);
				System.out.println(x + "," + y);
				if (y == 19) {
					y = 0; x++;
				}
				else
					y++;
			}
			numberFileReader.close();
		}
    }
    
    void getVals(){
        String curr;
        curr = StartXTextField.getText();
	if (curr.length() == 0) startX = 0;
        else startX = Integer.parseInt(curr);
			
	curr = StartYTextField.getText();
	if(curr.length() == 0) startY = 0;
	else startY = Integer.parseInt(curr);
			
	curr = EndXTextField.getText();
	if (curr.length() == 0) endX = 0;
	else endX = Integer.parseInt(curr);
			
	curr = EndYTextField.getText();
	if (curr.length() == 0) endY = 0;
	else endY = Integer.parseInt(curr);
    }
    
    void setText(List<Node> path){
        String coords = new String();
        for (int i = 0; i < path.size(); ++i)
	{
            Node curr = path.get(i);
            coords += "[" + curr.x + "," + curr.y + "]";
            if (i + 1 < path.size())
                coords += ",";
            else
                coords += "\n";
	}
        coords += path.get(path.size()-1).getG();
        OutputBoxText.setText(coords);
    }
    
    boolean validCoords(){
        if (startX > 19 || startX < 0 || startY > 19 || startY < 0 || endX > 19 || endX < 0 || endY > 19 || endY < 0)
            return false;
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GridLabel = new javax.swing.JLabel();
        NoteLabel = new javax.swing.JLabel();
        StartXTextField = new javax.swing.JTextField();
        EndXTextField = new javax.swing.JTextField();
        EndYTextField = new javax.swing.JTextField();
        StartYTextField = new javax.swing.JTextField();
        StartXCoordLabel = new javax.swing.JLabel();
        StartYCoordLabel = new javax.swing.JLabel();
        EndXCoordLabel = new javax.swing.JLabel();
        EndYCoordLabel = new javax.swing.JLabel();
        ChebysevButton = new javax.swing.JButton();
        EuclideanButton = new javax.swing.JButton();
        ManhattanButton = new javax.swing.JButton();
        OutputBox = new javax.swing.JScrollPane();
        OutputBoxText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GridLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        GridLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grid_Algorithms.PNG"))); // NOI18N
        GridLabel.setLabelFor(GridLabel);
        GridLabel.setText("Please Enter Start and End Coordinates and Then Select a Metric!");
        GridLabel.setToolTipText("");
        GridLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GridLabel.setFocusable(false);
        GridLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GridLabel.setMaximumSize(new java.awt.Dimension(450, 442));
        GridLabel.setMinimumSize(new java.awt.Dimension(450, 442));
        GridLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        NoteLabel.setText("Please Note: All Coordinates Should be Between 0 and 19");

        StartXTextField.setToolTipText("");

        EndXTextField.setToolTipText("");

        EndYTextField.setToolTipText("");

        StartYTextField.setToolTipText("");

        StartXCoordLabel.setText("Start X:");

        StartYCoordLabel.setText("Start Y:");

        EndXCoordLabel.setText("End X:");

        EndYCoordLabel.setText("End Y:");

        ChebysevButton.setBackground(new java.awt.Color(255, 204, 204));
        ChebysevButton.setText("Chebyshev");
        ChebysevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChebysevButtonActionPerformed(evt);
            }
        });

        EuclideanButton.setBackground(new java.awt.Color(204, 255, 255));
        EuclideanButton.setText("Euclidean");
        EuclideanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EuclideanButtonActionPerformed(evt);
            }
        });

        ManhattanButton.setBackground(new java.awt.Color(204, 255, 204));
        ManhattanButton.setText("Manhattan");
        ManhattanButton.setActionCommand("ManhattanButton");
        ManhattanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManhattanButtonActionPerformed(evt);
            }
        });

        OutputBoxText.setColumns(20);
        OutputBoxText.setRows(5);
        OutputBox.setViewportView(OutputBoxText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ChebysevButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EuclideanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManhattanButton)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(NoteLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StartXCoordLabel)
                                    .addComponent(EndXCoordLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EndXTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EndYCoordLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EndYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(StartXTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(StartYCoordLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StartYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(GridLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OutputBox)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GridLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartXTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartXCoordLabel)
                    .addComponent(StartYCoordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EndYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndXTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndXCoordLabel)
                    .addComponent(EndYCoordLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChebysevButton)
                    .addComponent(EuclideanButton)
                    .addComponent(ManhattanButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OutputBox, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChebysevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChebysevButtonActionPerformed
        getVals();
        if (validCoords()){
        ShortestPath runPath  = new ShortestPath(grid,"Chebyshev");
        List<Node> path = new LinkedList();
        path = runPath.aStarAlgorithm(startX, startY, endX, endY);
        setText(path);}
        else
            OutputBoxText.setText("Invalid Coordinates");
        
    }//GEN-LAST:event_ChebysevButtonActionPerformed

    private void EuclideanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EuclideanButtonActionPerformed
        getVals();
        if(validCoords()){
        ShortestPath runPath  = new ShortestPath(grid,"Chebyshev");
        List<Node> path = new LinkedList();
        path = runPath.aStarAlgorithm(startX, startY, endX, endY);
        setText(path);}
        else
            OutputBoxText.setText("Invalid Coordinates");
    }//GEN-LAST:event_EuclideanButtonActionPerformed

    private void ManhattanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManhattanButtonActionPerformed
        getVals();
        if (validCoords()){
        ShortestPath runPath  = new ShortestPath(grid,"Chebyshev");
        List<Node> path = new LinkedList();
        path = runPath.aStarAlgorithm(startX, startY, endX, endY);
        setText(path);}
        else
            OutputBoxText.setText("Invalid Coordinates");
    }//GEN-LAST:event_ManhattanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShortestPathsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShortestPathsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShortestPathsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShortestPathsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               try{
                   new ShortestPathsGUI().setVisible(true);
               }
               catch(FileNotFoundException e){
                   e.printStackTrace();
               }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChebysevButton;
    private javax.swing.JLabel EndXCoordLabel;
    private javax.swing.JTextField EndXTextField;
    private javax.swing.JLabel EndYCoordLabel;
    private javax.swing.JTextField EndYTextField;
    private javax.swing.JButton EuclideanButton;
    private javax.swing.JLabel GridLabel;
    private javax.swing.JButton ManhattanButton;
    private javax.swing.JLabel NoteLabel;
    private javax.swing.JScrollPane OutputBox;
    private javax.swing.JTextArea OutputBoxText;
    private javax.swing.JLabel StartXCoordLabel;
    private javax.swing.JTextField StartXTextField;
    private javax.swing.JLabel StartYCoordLabel;
    private javax.swing.JTextField StartYTextField;
    // End of variables declaration//GEN-END:variables
}
